//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APICasoEstudio2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CasoEstudioKNEntities : DbContext
    {
        public CasoEstudioKNEntities()
            : base("name=CasoEstudioKNEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CasasSistema> CasasSistema { get; set; }
    
        public virtual int ActualizarAlquiler(Nullable<long> idCasa, string descripcionCasa, Nullable<decimal> precioCasa, string usuarioAlquiler, Nullable<System.DateTime> fechaAlquiler)
        {
            var idCasaParameter = idCasa.HasValue ?
                new ObjectParameter("IdCasa", idCasa) :
                new ObjectParameter("IdCasa", typeof(long));
    
            var descripcionCasaParameter = descripcionCasa != null ?
                new ObjectParameter("DescripcionCasa", descripcionCasa) :
                new ObjectParameter("DescripcionCasa", typeof(string));
    
            var precioCasaParameter = precioCasa.HasValue ?
                new ObjectParameter("PrecioCasa", precioCasa) :
                new ObjectParameter("PrecioCasa", typeof(decimal));
    
            var usuarioAlquilerParameter = usuarioAlquiler != null ?
                new ObjectParameter("UsuarioAlquiler", usuarioAlquiler) :
                new ObjectParameter("UsuarioAlquiler", typeof(string));
    
            var fechaAlquilerParameter = fechaAlquiler.HasValue ?
                new ObjectParameter("FechaAlquiler", fechaAlquiler) :
                new ObjectParameter("FechaAlquiler", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActualizarAlquiler", idCasaParameter, descripcionCasaParameter, precioCasaParameter, usuarioAlquilerParameter, fechaAlquilerParameter);
        }
    
        public virtual ObjectResult<ObtenerCasasDisponibles_Result> ObtenerCasasDisponibles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerCasasDisponibles_Result>("ObtenerCasasDisponibles");
        }
    
        public virtual ObjectResult<ObtenerInfoCasa_Result> ObtenerInfoCasa(Nullable<long> idCasa)
        {
            var idCasaParameter = idCasa.HasValue ?
                new ObjectParameter("IdCasa", idCasa) :
                new ObjectParameter("IdCasa", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerInfoCasa_Result>("ObtenerInfoCasa", idCasaParameter);
        }
    
        public virtual ObjectResult<ObtenerInfoCasas_Result> ObtenerInfoCasas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerInfoCasas_Result>("ObtenerInfoCasas");
        }
    }
}
